{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
    name: featuretools
    version: {{ data.get('version') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    {% if GIT_DESCRIBE_NUMBER|int == 0 %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_0
    {% else %}string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}{% endif %}

source:
    path: ../

requirements:
  build:
    - python {{ python }}
    - setuptools >=3.3
    {% for req in data.get('setup_requires') %}
    - {{ req|replace('\n', '') }}
    {% endfor %}
    {% for req in data.get('install_requires') %}
    - {{ req|replace('\n', '') }}
    {% endfor %}


  run:
    - python
    {% for req in data.get('install_requires') %}
    - {{ req|replace('\n', '') }}
    {% endfor %}
test:
  imports:
    - featuretools
  requires:
    - pytest==3.5.1
    {% for req in data.get('tests_require') %}
    - {{ req|replace('\n', '') }}
    {% endfor %}
  source_files:
    - featuretools/*


about:
  home: https://featuretools.com
  license: BSD
  license_file: LICENSE
